name: Set up Zig Toolchain
description: Set up Zig in GitHub Actions for use in your workflow.
author: Jassiel Ovando

branding:
  color: yellow
  icon: zap
inputs:
  version:
    description: The version to install, either a specific, master (from Git development branch) or default to the latest stable.
    default: latest
  cache:
    description: Enable caching of build artifacts.
    default: "false"
  cache-dependency-path:
    description: Dependency files affecting cache (glob).
    default: |
      build.zig
      build.zig.zon
  cache-path:
    description: The paths to cache, separated by newlines. Defaults to Zig's cache and output paths.
    default: |
      **/.zig-cache
      **/zig-out
  target:
    description: Zig target to improve cache correctness

runs:
  using: composite
  steps:
    - name: Install Zig
      shell: bash
      run: |
        if command -v python3 >/dev/null 2>&1; then
          python3 "${{ github.action_path }}/scripts/installer.py" --version "${{ inputs.version }}"
        elif command -v python >/dev/null 2>&1; then
          python "${{ github.action_path }}/scripts/installer.py" --version "${{ inputs.version }}"
        elif command -v py >/dev/null 2>&1; then
          py -3 "${{ github.action_path }}/scripts/installer.py" --version "${{ inputs.version }}"
        else
          echo "Python runtime not found on PATH" >&2
          exit 1
        fi

    - name: Compute cache key
      id: cache-key
      if: inputs.cache == 'true'
      shell: bash
      run: |
        set -e

        TARGET="${{ inputs.target }}"
        [ -z "$TARGET" ] && TARGET="default"

        KEY="zig-${{ runner.os }}-${{ inputs.version }}-${TARGET}-${{ hashFiles(inputs.cache-dependency-path) }}"

        echo "key=$KEY" >> $GITHUB_OUTPUT

    - name: Restore cache
      if: inputs.cache == 'true'
      uses: actions/cache@v5
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ steps.cache-key.outputs.key }}
